name: mywebsite
description: my personnal website

scripts:
  dev: vite dev
  build: vite build
  preview: vite preview
  lint: prettier --plugin-search-dir . --check . && eslint .
  format: prettier --plugin-search-dir . --write .
